ALTER TABLE "Users"
    ALTER COLUMN "name" TYPE varchar(255) COLLATE public.numeric_text;

-- INI KALAU MAU MENGHAPUS COLLATION DI KOLOM TERSEBUT YA
-- ALTER TABLE "Users"
--   ALTER COLUMN "name"
--   TYPE varchar(255) COLLATE DEFAULT;
